#ifndef _COLORS_H_
#define _COLORS_H_

#define COLOR_BLACK              0x000000
#define COLOR_WHITE              0xFFFFFF
#define COLOR_BLUE               0x0000FF

#define COLOR_MENU_BACKGROUND    0x5C7A63
#define COLOR_MENU_TITLE         COLOR_BLUE
#define COLOR_CURSOR             COLOR_WHITE
#define COLOR_MENU_TEXT          COLOR_BLACK
#define COLOR_MENU_UNDERLINE     COLOR_BLACK

#define COLOR_BUTTON_DARK_NAVY   0x333366
#define COLOR_BUTTON_LIGHT_NAVY  0x5555AA
#define COLOR_BUTTON_DARK_GRAY   0x555555
#define COLOR_BUTTON_SILVER      0xCCCCCC
#define COLOR_BUTTON_BORDER      COLOR_WHITE
#define COLOR_BUTTON_TEXT        COLOR_WHITE

#define COLOR_HUD_BORDER         COLOR_BLACK
#define COLOR_HUD_PANEL          0x111111
#define COLOR_HUD_BAR_BACKGROUND 0x1A1A1A
#define COLOR_BOOST_FILL         0x007BFF
#define COLOR_COUNTDOWN_TEXT     0xFFD166
#define COLOR_SPEEDO_NEEDLE      0xFF0000
#define COLOR_SPEEDO_PIVOT       0xCCCCCC

#endif /* _COLORS_H_ */
